// Full-Day Cyber Security Job Routine & Roadmap-Aligned Timetable Constants

export interface RoutineSlot {
  id: string;
  time: string;
  startTime: string;
  endTime: string;
  title: string;
  type: 'health' | 'cyber-theory' | 'hands-on-lab' | 'practical-cyber' | 'job-prep' | 'exercise' | 'nutrition' | 'rest' | 'revision';
  category: string;
  priority: 'high' | 'medium' | 'low';
  reminderMinutes: number;
  description: string;
  notes?: string;
  icon: string;
  color: string;
}

export interface RoadmapRoutinePreset {
  id: string;
  title: string;
  subtitle: string;
  phaseNumber: number;
  badge: string;
  color: string;
  category: string;
  theoryTopic: string;
  theorySubtopics: string[];
  theoryGoal: string;
  handsOnTopic: string;
  handsOnCommands: string[];
  handsOnLab: string;
  practicalTopic: string;
  practicalDetails: string;
  jobPrepDetails: string;
  revisionTopic: string;
  revisionQuestions: string[];
}

export const ROADMAP_ROUTINE_PRESETS: RoadmapRoutinePreset[] = [
  {
    id: 'day-1',
    title: 'Phase 1 · Day 1',
    subtitle: 'Computer Hardware, OS & Processes',
    phaseNumber: 1,
    badge: 'DAY 1',
    color: '#00e5ff',
    category: 'Cyber Security Fundamentals',
    theoryTopic: 'Computer Architecture & OS Internals',
    theorySubtopics: [
      'OS Architecture (Windows NT Kernel vs Linux Kernel)',
      'CPU, Volatile RAM vs Non-volatile Storage',
      'What is a Process and how threads execute in memory',
      'Background Services (Windows) vs Daemons (Linux)',
    ],
    theoryGoal: 'Understand how software translates to CPU cycles and memory spaces.',
    handsOnTopic: 'Task Manager & Windows Services Lab',
    handsOnCommands: ['Task Manager (Performance tab)', 'services.msc', 'cmd: tasklist'],
    handsOnLab: 'Open Task Manager, sort by memory, identify svchost instances, and inspect background services in services.msc.',
    practicalTopic: 'Process & Memory Analysis',
    practicalDetails: 'Map active processes to their executable paths and observe resource utilization under load.',
    jobPrepDetails: 'Write concise definitions for OS, Kernel, Process, and Thread. Optimize LinkedIn headline for Cyber Security aspirant.',
    revisionTopic: 'Hardware & Process Recall',
    revisionQuestions: [
      'What is the fundamental difference between RAM and Storage?',
      'What is a process and how does it allocate memory?',
      'Why do security analysts need to understand background services?',
    ],
  },
  {
    id: 'day-2',
    title: 'Phase 1 · Day 2',
    subtitle: 'Internet & Client-Server Architecture',
    phaseNumber: 1,
    badge: 'DAY 2',
    color: '#00e5ff',
    category: 'Networking',
    theoryTopic: 'Internet Fundamentals & Client-Server Roles',
    theorySubtopics: [
      'What is the Internet and global packet routing?',
      'Client vs Server roles in network communication',
      'Domain Names vs Numerical IP Addresses',
      'End-to-End flow: What happens when you type a URL?',
    ],
    theoryGoal: 'Explain how browsers request web pages from remote web servers.',
    handsOnTopic: 'Network Diagnostic Commands Lab',
    handsOnCommands: ['ping google.com', 'nslookup google.com', 'tracert 8.8.8.8'],
    handsOnLab: 'Run ping to test ICMP latency and tracert to see all intermediate router hops to Google DNS.',
    practicalTopic: 'Packet Hop & Latency Inspection',
    practicalDetails: 'Observe TTL (Time to Live) values and analyze latency differences between local gateway and external servers.',
    jobPrepDetails: 'Create a clear diagram of the Client-Server request-response cycle and save in your portfolio notes.',
    revisionTopic: 'Internet Architecture Recall',
    revisionQuestions: [
      'What is the difference between a Client and a Server?',
      'What information does the ping command provide?',
      'How does tracert determine the path to a destination?',
    ],
  },
  {
    id: 'day-3',
    title: 'Phase 1 · Day 3',
    subtitle: 'IP Addressing & Subnetting Basics',
    phaseNumber: 1,
    badge: 'DAY 3',
    color: '#00e5ff',
    category: 'Networking',
    theoryTopic: 'IPv4 Structure, Public vs Private IPs',
    theorySubtopics: [
      'IPv4 32-bit architecture & 4 octets breakdown',
      'Private IP ranges (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16)',
      'Public IP routing vs Private Network Address Translation (NAT)',
      'Loopback address (127.0.0.1 / localhost)',
    ],
    theoryGoal: 'Distinguish between internal LAN addresses and internet-routable public IPs.',
    handsOnTopic: 'IP Configuration & Localhost Lab',
    handsOnCommands: ['ipconfig /all (Windows)', 'ip addr (Linux)', 'ping 127.0.0.1'],
    handsOnLab: 'Find your Private IP, Subnet Mask, Default Gateway, and MAC address using ipconfig /all.',
    practicalTopic: 'Network Adapter & Gateway Triage',
    practicalDetails: 'Verify localhost TCP stack responsiveness and document the role of the default gateway router.',
    jobPrepDetails: 'Practice explaining Public vs Private IP in simple terms as expected in SOC Tier 1 interviews.',
    revisionTopic: 'IP Addressing Self-Check',
    revisionQuestions: [
      'What are the 3 RFC 1918 Private IP address ranges?',
      'Why is NAT needed when connecting to the Internet?',
      'What is the purpose of the 127.0.0.1 loopback address?',
    ],
  },
  {
    id: 'day-4',
    title: 'Phase 1 · Day 4',
    subtitle: 'DNS (Domain Name System) Deep Dive',
    phaseNumber: 1,
    badge: 'DAY 4',
    color: '#00e5ff',
    category: 'Networking',
    theoryTopic: 'DNS Hierarchy & Resolution Architecture',
    theorySubtopics: [
      'DNS as the phonebook of the Internet',
      'Hierarchy: Root servers (.) → TLD servers (.com) → Authoritative nameservers',
      'Recursive DNS resolvers (8.8.8.8, 1.1.1.1)',
      'Core Record types: A, AAAA, CNAME, MX, TXT, NS',
    ],
    theoryGoal: 'Trace the complete DNS lookup tree from browser cache to authoritative answer.',
    handsOnTopic: 'DNS Record Querying Lab',
    handsOnCommands: ['nslookup -type=A google.com', 'nslookup -type=MX google.com', 'ipconfig /flushdns'],
    handsOnLab: 'Query A records and Mail Exchanger (MX) records for major domains and flush the local DNS cache.',
    practicalTopic: 'DNS Cache & Resolution Audit',
    practicalDetails: 'Inspect your local DNS resolver IP and compare response times across public resolvers (Google vs Cloudflare).',
    jobPrepDetails: 'Write a step-by-step interview script explaining how DNS resolution works end-to-end.',
    revisionTopic: 'DNS Mechanics Recall',
    revisionQuestions: [
      'What happens when a DNS record is not in your local cache?',
      'What is the difference between an A record and a CNAME record?',
      'Why do attackers target DNS (e.g. DNS Spoofing/Poisoning)?',
    ],
  },
  {
    id: 'day-5',
    title: 'Phase 1 · Day 5',
    subtitle: 'Ports & Common Protocols',
    phaseNumber: 1,
    badge: 'DAY 5',
    color: '#00e5ff',
    category: 'Networking',
    theoryTopic: 'Network Ports & Protocol Mappings',
    theorySubtopics: [
      'What is a Port? (Virtual communication endpoint, range 0–65535)',
      'Port 22 (SSH), Port 53 (DNS), Port 80 (HTTP), Port 443 (HTTPS)',
      'Port 21 (FTP), Port 25 (SMTP), Port 3389 (RDP)',
      'The Golden Mapping: IP → Port → Protocol → Service',
    ],
    theoryGoal: 'Master standard port numbers and associate ports with target services.',
    handsOnTopic: 'Active Listening Ports Lab',
    handsOnCommands: ['netstat -ano (Windows)', 'ss -tuln (Linux)', 'curl -I http://google.com:80'],
    handsOnLab: 'Run netstat -ano to list all LISTENING ports on your computer and map their PIDs to running applications.',
    practicalTopic: 'Port & Service Mapping Analysis',
    practicalDetails: 'Identify open ports, understand why unneeded open ports increase attack surface, and learn port classification.',
    jobPrepDetails: 'Memorize top 15 common cybersecurity ports with flashcards for instant recall in interviews.',
    revisionTopic: 'Ports & Protocol Quick Fire',
    revisionQuestions: [
      'Which port is used by HTTPS, SSH, DNS, and RDP?',
      'What is the difference between an IP address and a Port number?',
      'What does netstat -ano display?',
    ],
  },
  {
    id: 'day-6',
    title: 'Phase 1 · Day 6',
    subtitle: 'HTTP & HTTPS Protocol Dissection',
    phaseNumber: 1,
    badge: 'DAY 6',
    color: '#00e5ff',
    category: 'Web Security',
    theoryTopic: 'HTTP Request/Response Anatomy & TLS',
    theorySubtopics: [
      'HTTP Methods: GET, POST, PUT, DELETE, OPTIONS',
      'HTTP Status Codes (200 OK, 301 Redirect, 403 Forbidden, 404 Not Found, 500 Server Error)',
      'Headers (User-Agent, Content-Type, Authorization, Cookie)',
      'HTTP vs HTTPS: TLS Handshake & Certificate Validation',
    ],
    theoryGoal: 'Dissect web traffic headers, cookies, and status codes in detail.',
    handsOnTopic: 'Browser DevTools & cURL Inspection',
    handsOnCommands: ['curl -v https://httpbin.org/get', 'DevTools (F12) → Network Tab'],
    handsOnLab: 'Open browser DevTools Network tab, inspect request/response headers of a login page, and examine cookies.',
    practicalTopic: 'HTTP Header Security Triage',
    practicalDetails: 'Inspect security response headers (Content-Security-Policy, Strict-Transport-Security, X-Frame-Options).',
    jobPrepDetails: 'Document the 5 major HTTP status code classes (1xx, 2xx, 3xx, 4xx, 5xx) in your technical notes.',
    revisionTopic: 'HTTP/HTTPS Fundamentals',
    revisionQuestions: [
      'What is the difference between HTTP GET and POST methods?',
      'What makes HTTPS secure compared to plaintext HTTP?',
      'What purpose do HTTP cookies serve in web sessions?',
    ],
  },
  {
    id: 'day-7',
    title: 'Phase 1 · Day 7',
    subtitle: 'Phase 1 Assessment & Self-Test',
    phaseNumber: 1,
    badge: 'DAY 7',
    color: '#00ff9d',
    category: 'Revision',
    theoryTopic: 'Phase 1 Comprehensive Foundation Review',
    theorySubtopics: [
      'Full revision of Computer, Internet, IP, DNS, Ports, and HTTP',
      'End-to-end synthesis: "What happens when you type google.com in a browser?"',
      'Weak topic consolidation and note finalization',
      'Prepare for Phase 2: Deep Networking',
    ],
    theoryGoal: 'Achieve 8/10+ on the Phase 1 Foundation Assessment without looking at notes.',
    handsOnTopic: 'Comprehensive Lab Test & Pre-Security Room',
    handsOnCommands: ['Complete TryHackMe Pre-Security Room', 'Review all command outputs'],
    handsOnLab: 'Walk through an end-to-end network diagnosis test using ping, tracert, nslookup, and netstat.',
    practicalTopic: 'Oral / Written Self-Assessment',
    practicalDetails: 'Answer all 10 evaluation questions in your own words with complete technical precision.',
    jobPrepDetails: 'Create a GitHub repository named `cybersecurity-journey` and commit your Phase 1 study notes.',
    revisionTopic: 'The 10-Question Master Quiz',
    revisionQuestions: [
      '1. IP kya hai aur MAC address se kaise alag hai?',
      '2. DNS ka primary role kya hai?',
      '3. Port kya hota hai aur IP ke sath kaise work karta hai?',
      '4. TCP vs UDP fundamental difference?',
      '5. HTTP vs HTTPS security difference?',
      '6. Client vs Server architecture?',
      '7. Router vs Firewall role?',
      '8. Port 443 protocol?',
      '9. Browser google.com flow?',
      '10. Private IP vs Public IP?',
    ],
  },
  {
    id: 'phase-2',
    title: 'Phase 2',
    subtitle: 'Networking Fundamentals (Weeks 2–4)',
    phaseNumber: 2,
    badge: 'PHASE 2',
    color: '#3b82f6',
    category: 'Networking',
    theoryTopic: 'Networking Protocols, TCP 3-Way Handshake & Firewalls',
    theorySubtopics: [
      'TCP vs UDP (Reliable vs Connectionless transport)',
      'TCP 3-Way Handshake (SYN → SYN-ACK → ACK)',
      'OSI 7 Layers vs TCP/IP 4 Layers architecture',
      'Firewalls (Stateful vs Stateless) & Network Address Translation (NAT)',
      'VPNs, Proxies, and Encrypted tunnels',
    ],
    theoryGoal: 'Master network packet traversal, packet encapsulation, and firewall filtering rules.',
    handsOnTopic: 'Wireshark Packet Dissection Lab',
    handsOnCommands: ['Wireshark filter: tcp.port == 443', 'Wireshark filter: dns', 'tcpdump -i eth0 -nn'],
    handsOnLab: 'Capture live network traffic in Wireshark, follow a TCP stream, and observe the 3-way handshake.',
    practicalTopic: 'Network Traffic Analysis & Protocol Triage',
    practicalDetails: 'Filter out ARP, DNS, and TLS traffic in Wireshark and identify abnormal packet retransmissions.',
    jobPrepDetails: 'Practice explaining the TCP 3-Way Handshake and OSI Model layers in mock interview style.',
    revisionTopic: 'Networking Core Concepts Recall',
    revisionQuestions: [
      'Explain the TCP 3-Way Handshake step-by-step with packet flags.',
      'What layer of the OSI model does a Router operate on vs a Switch?',
      'How does a Stateful Firewall track active network sessions?',
    ],
  },
  {
    id: 'phase-3',
    title: 'Phase 3',
    subtitle: 'Linux Basics & VM Security Lab (Weeks 5–6)',
    phaseNumber: 3,
    badge: 'PHASE 3',
    color: '#22c55e',
    category: 'Linux',
    theoryTopic: 'Linux Administration, Permissions & Security Hardening',
    theorySubtopics: [
      'Linux Filesystem Hierarchy (/etc, /var/log, /home, /bin, /dev)',
      'Users, Groups, /etc/passwd, /etc/shadow, and sudoers',
      'Permissions: Read/Write/Execute (rwx), Octal values (755, 644, 600), SUID & SGID',
      'Systemd Service Management (systemctl start/stop/status/enable)',
      'SSH Hardening & Key Pair authentication',
    ],
    theoryGoal: 'Build and administer a secure Linux VM with least privilege principles.',
    handsOnTopic: 'Linux Security VM Hardening Lab',
    handsOnCommands: ['chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys', 'grep -r "Failed password" /var/log/auth.log', 'systemctl status sshd', 'ss -tuln'],
    handsOnLab: 'Setup an Ubuntu VM, create standard & admin users, disable root SSH login, and audit system authentication logs.',
    practicalTopic: 'Auth Log Inspection & Privilege Audit',
    practicalDetails: 'Parse /var/log/auth.log using grep and awk to extract failed SSH login attempts and identify attacker IPs.',
    jobPrepDetails: 'Document your Linux VM hardening steps on GitHub with Markdown and screenshots.',
    revisionTopic: 'Linux Commands & Permissions Recall',
    revisionQuestions: [
      'What does `chmod 755` vs `chmod 600` grant?',
      'What is the security risk of SUID bit on sensitive binaries?',
      'Where are Linux authentication logs located and what do they record?',
    ],
  },
  {
    id: 'phase-4',
    title: 'Phase 4',
    subtitle: 'Cyber Security Fundamentals (Weeks 7–8)',
    phaseNumber: 4,
    badge: 'PHASE 4',
    color: '#a855f7',
    category: 'Cyber Security Fundamentals',
    theoryTopic: 'CIA Triad, Access Control & Threat Modeling',
    theorySubtopics: [
      'CIA Triad: Confidentiality (Encryption), Integrity (Hashing), Availability (Redundancy)',
      'AAA Framework: Authentication vs Authorization vs Accounting',
      'Principle of Least Privilege, Defense-in-Depth, Zero Trust Architecture',
      'Threat Actor vs Vulnerability vs Exploit vs Risk calculation',
      'Common Attacks: Phishing, Ransomware, DDoS, MitM, Brute-force',
    ],
    theoryGoal: 'Analyze threat landscapes and apply defense-in-depth principles to system architectures.',
    handsOnTopic: 'Cryptography & Threat Analysis Lab',
    handsOnCommands: ['sha256sum <file>', 'openssl enc -aes-256-cbc', 'gpg --encrypt'],
    handsOnLab: 'Generate SHA-256 hashes to verify file integrity and simulate symmetric encryption with OpenSSL.',
    practicalTopic: 'Attack Surface & Threat Modeling Matrix',
    practicalDetails: 'Perform a STRIDE threat modeling exercise for a standard web application login system.',
    jobPrepDetails: 'Prepare structured answers for "What is the CIA Triad?" and "Explain Zero Trust Architecture".',
    revisionTopic: 'Core Cyber Security Principles',
    revisionQuestions: [
      'What is the difference between Encryption, Hashing, and Encoding?',
      'How does Defense-in-Depth protect against single points of failure?',
      'What is the difference between Authentication and Authorization?',
    ],
  },
  {
    id: 'phase-5',
    title: 'Phase 5',
    subtitle: 'Web Application Security & OWASP Top 10 (Weeks 9–11)',
    phaseNumber: 5,
    badge: 'PHASE 5',
    color: '#ec4899',
    category: 'Web Security',
    theoryTopic: 'OWASP Top 10 Vulnerabilities & Web Mechanics',
    theorySubtopics: [
      'OWASP Top 10 Vulnerability taxonomy and impact',
      'SQL Injection (In-band, Error-based, Blind SQLi)',
      'Cross-Site Scripting (XSS - Reflected, Stored, DOM)',
      'Broken Access Control & Insecure Direct Object References (IDOR)',
      'Server-Side Request Forgery (SSRF) & Security Misconfigurations',
    ],
    theoryGoal: 'Understand root causes of web vulnerabilities and write effective remediation code.',
    handsOnTopic: 'PortSwigger Web Security Academy Labs',
    handsOnCommands: ['Burp Suite Proxy Interceptor', 'Repeater tab parameter tampering', 'PortSwigger Academy labs'],
    handsOnLab: 'Intercept HTTP requests in Burp Suite, test for SQL Injection in login parameters, and execute XSS payloads safely.',
    practicalTopic: 'Vulnerability Analysis & Patching',
    practicalDetails: 'Analyze vulnerable source code, understand SQL parameterized queries, and implement input sanitization.',
    jobPrepDetails: 'Write 2 vulnerability triage reports documenting vulnerability impact, reproduction steps, and fixes.',
    revisionTopic: 'OWASP Top 10 Mastery Recall',
    revisionQuestions: [
      'How do Parameterized Queries prevent SQL Injection?',
      'What is the difference between Stored XSS and Reflected XSS?',
      'What HTTP cookie flags protect against session hijacking?',
    ],
  },
  {
    id: 'phase-6',
    title: 'Phase 6',
    subtitle: 'Python for Cyber Security & Automation (Weeks 12–13)',
    phaseNumber: 6,
    badge: 'PHASE 6',
    color: '#eab308',
    category: 'Python',
    theoryTopic: 'Python Socket Programming, Requests & Regex',
    theorySubtopics: [
      'Python `socket` module for raw TCP connection and banner grabbing',
      'Python `requests` for HTTP automation and API interaction',
      '`re` (Regular Expressions) for parsing logs, IPs, and timestamps',
      '`hashlib` and `bcrypt` for password hashing and validation',
    ],
    theoryGoal: 'Build custom security automation scripts in Python to streamline security tasks.',
    handsOnTopic: 'Port Scanner & Log Parser Scripting Lab',
    handsOnCommands: ['python port_scanner.py -t 127.0.0.1 -p 1-1000', 'python log_analyzer.py auth.log'],
    handsOnLab: 'Code a multi-threaded TCP Port Scanner and an automated auth.log parser that extracts failed login attempts.',
    practicalTopic: 'Custom Tooling & Password Hasher',
    practicalDetails: 'Build a password hash generator supporting SHA-256 and bcrypt salting with verification checks.',
    jobPrepDetails: 'Upload your Python security tools to GitHub with clear docstrings, requirements.txt, and demo GIFs.',
    revisionTopic: 'Python Security Scripting Concepts',
    revisionQuestions: [
      'How does Python `socket.connect_ex()` determine if a port is open?',
      'Why is regex essential for SOC log parsing?',
      'Why is simple MD5/SHA-256 hashing insecure for passwords without salting?',
    ],
  },
  {
    id: 'phase-7',
    title: 'Phase 7',
    subtitle: 'SOC Analyst & SIEM / Splunk (Weeks 14–17)',
    phaseNumber: 7,
    badge: 'PHASE 7',
    color: '#06b6d4',
    category: 'SOC',
    theoryTopic: 'SOC Operations, Alert Triage & SIEM SPL Queries',
    theorySubtopics: [
      'SOC Roles: Tier 1 Triage, Tier 2 Incident Response, Tier 3 Hunting',
      'Terminology: Alert vs Event vs Incident, IOCs, TTPs, False Positives',
      'Windows Security Event Logs (Event ID 4624 Successful, 4625 Failed Login)',
      'Splunk Search Processing Language (SPL) & Microsoft Sentinel KQL',
      'MITRE ATT&CK Framework matrix mapping',
    ],
    theoryGoal: 'Triage live security alerts, identify true positives, and write professional incident escalation reports.',
    handsOnTopic: 'Splunk / SIEM Investigation Lab',
    handsOnCommands: ['index=security EventCode=4625 | stats count by src_ip', 'KQL: SecurityEvent | where EventID == 4625'],
    handsOnLab: 'Run Splunk SPL queries against mock security datasets to detect brute-force attacks and privilege escalation.',
    practicalTopic: 'Incident Triage & False Positive Elimination',
    practicalDetails: 'Analyze suspicious IP reputation (VirusTotal, AbuseIPDB) and determine true vs false positive alerts.',
    jobPrepDetails: 'Practice 10 realistic SOC Analyst Tier 1 interview scenarios and apply to 3 active SOC openings.',
    revisionTopic: 'SOC & Event ID Quick Fire',
    revisionQuestions: [
      'What is the significance of Windows Event ID 4624 vs 4625?',
      'What are the 5 core steps when investigating a suspicious login alert?',
      'What is an IOC and how do you verify it using threat intelligence?',
    ],
  },
  {
    id: 'phase-8',
    title: 'Phase 8',
    subtitle: 'Incident Response Lifecycle & Playbooks (Weeks 18–19)',
    phaseNumber: 8,
    badge: 'PHASE 8',
    color: '#ff3b5c',
    category: 'SOC',
    theoryTopic: 'NIST & SANS Incident Response Lifecycle',
    theorySubtopics: [
      'The 6 Steps: Preparation → Detection → Analysis → Containment → Eradication → Recovery → Lessons Learned',
      'Phishing Email Investigation Playbook (Headers, Attachments, URL detonation)',
      'Malware Infection & Endpoint Host Isolation Playbook',
      'Compromised User Account & Password Reset Containment',
    ],
    theoryGoal: 'Execute incident response playbooks methodically during critical security breaches.',
    handsOnTopic: 'Phishing & Malware Analysis Lab',
    handsOnCommands: ['Inspect email .eml headers', 'Extract SPF/DKIM/DMARC status', 'Check file hash in VirusTotal'],
    handsOnLab: 'Analyze a simulated phishing email, inspect headers for sender spoofing, and extract malicious attachments.',
    practicalTopic: 'Incident Containment Playbook Walkthrough',
    practicalDetails: 'Draft a complete containment and recovery plan for a ransomware outbreak scenario in an enterprise network.',
    jobPrepDetails: 'Memorize the PICERL steps for scenario-based technical interviews.',
    revisionTopic: 'Incident Response Framework Recall',
    revisionQuestions: [
      'What are the 6 stages of the NIST Incident Response lifecycle?',
      'What is the immediate action when a host is infected with active malware?',
      'Why is the "Lessons Learned" phase critical after an incident?',
    ],
  },
  {
    id: 'phase-9',
    title: 'Phase 9',
    subtitle: 'Hands-on Legal Labs & CTF Practice (Weeks 20–21)',
    phaseNumber: 9,
    badge: 'PHASE 9',
    color: '#f97316',
    category: 'CTF',
    theoryTopic: 'Lab Methodology & Continuous Skill Sharpening',
    theorySubtopics: [
      'TryHackMe SOC Level 1 & Complete Beginner pathways',
      'PortSwigger Web Security Academy practitioner rooms',
      'Hack The Box Academy network enumeration and Linux rooms',
      'Documentation rule: Vulnerability, Tool, Command, Mitigation',
    ],
    theoryGoal: 'Reach top percentile ranking on TryHackMe and build an undeniable portfolio of lab walkthroughs.',
    handsOnTopic: 'Intensive CTF / Lab Walkthrough Lab',
    handsOnCommands: ['Nmap service scan: nmap -sC -sV -oN scan.txt <target>', 'Gobuster directory enum: gobuster dir -u <url> -w wordlist.txt'],
    handsOnLab: 'Complete 1 full TryHackMe SOC room or PortSwigger lab and document the step-by-step triage writeup.',
    practicalTopic: 'Mitigation & Defense Documentation',
    practicalDetails: 'Write a professional remediation guide for every vulnerability exploited during lab practice.',
    jobPrepDetails: 'Add your TryHackMe badge and completed certifications to LinkedIn and resume.',
    revisionTopic: 'Lab Techniques & Tool Review',
    revisionQuestions: [
      'What is the difference between active vs passive reconnaissance?',
      'How does Nmap -sV determine service version information?',
      'What defensive measures prevent directory brute forcing?',
    ],
  },
  {
    id: 'phase-10',
    title: 'Phase 10',
    subtitle: '3 Capstones, Resume & Job Applications (Weeks 22–24)',
    phaseNumber: 10,
    badge: 'PHASE 10',
    color: '#00ff9d',
    category: 'Projects',
    theoryTopic: 'Portfolio Architecture, System Design & Interview Mastery',
    theorySubtopics: [
      'Project 1: SOC Log Analyzer Engine (Python + Regex + HTML Report)',
      'Project 2: Automated Lab Vulnerability & Service Scanner (Python)',
      'Project 3: Security Monitoring & SIEM Dashboard (FastAPI + React)',
      'Tailoring resume keywords for SOC Analyst & Cyber Security roles',
      'Behavioral & STAR technique interview strategies',
    ],
    theoryGoal: 'Publish 3 standout portfolio projects on GitHub and secure a Cyber Security job by December 2026! 🎉',
    handsOnTopic: 'Capstone Project Code & Deploy Lab',
    handsOnCommands: ['git init && git add . && git commit -m "Initial commit"', 'docker-compose up --build'],
    handsOnLab: 'Polish Project 3 (Security Monitoring Dashboard) with live WebSocket events and upload to GitHub with live demo.',
    practicalTopic: 'Job Application Blitz & Recruiter Outreach',
    practicalDetails: 'Submit 3–5 high-quality customized job applications on LinkedIn and Naukri, and connect with 5 security recruiters.',
    jobPrepDetails: 'Conduct a full 45-minute mock technical interview covering Networking, Linux, Web Security, SOC, and Projects.',
    revisionTopic: 'Final Job-Readiness Checklist',
    revisionQuestions: [
      'Can you explain the architecture and key challenges of your 3 projects?',
      'Are you confident answering both technical and scenario-based SOC questions?',
      'Is your resume tailored with relevant certifications, labs, and GitHub links?',
    ],
  },
];

export const MASTER_ROUTINE: RoutineSlot[] = [
  {
    id: 'routine-1',
    time: '6:45 AM',
    startTime: '06:45',
    endTime: '07:00',
    title: '🌅 Wake up & Morning Routine',
    type: 'health',
    category: 'Revision',
    priority: 'high',
    reminderMinutes: 0,
    description: 'Water, glucose/diabetes check, fresh hona, 5-10 min desk organize.',
    icon: 'sunny',
    color: '#00e5ff',
  },
  {
    id: 'routine-2',
    time: '7:00 AM',
    startTime: '07:00',
    endTime: '07:15',
    title: '💉 Morning Insulin Routine',
    type: 'health',
    category: 'Revision',
    priority: 'high',
    reminderMinutes: 5,
    description: 'Regular insulin dose as prescribed.',
    icon: 'medkit',
    color: '#ff3b5c',
  },
  {
    id: 'routine-3',
    time: '7:30 AM',
    startTime: '07:30',
    endTime: '08:00',
    title: '🍽️ Healthy Breakfast',
    type: 'nutrition',
    category: 'Revision',
    priority: 'medium',
    reminderMinutes: 10,
    description: 'Daliya, eggs/paneer/soy/curd, optional green tea (no sugar).',
    icon: 'restaurant',
    color: '#00ff9d',
  },
  {
    id: 'routine-4',
    time: '8:00 AM',
    startTime: '08:00',
    endTime: '08:20',
    title: '🧠 Morning Walk & Fresh Air',
    type: 'exercise',
    category: 'Revision',
    priority: 'medium',
    reminderMinutes: 5,
    description: 'Light 20-min morning walk and stretching for energy.',
    icon: 'walk',
    color: '#00e5ff',
  },
  {
    id: 'routine-5',
    time: '8:30–10:30 AM',
    startTime: '08:30',
    endTime: '10:30',
    title: '💻 Cyber Security Theory (Deep Work 1)',
    type: 'cyber-theory',
    category: 'Cyber Security Fundamentals',
    priority: 'high',
    reminderMinutes: 15,
    description: 'Deep theoretical concepts. Rule: Video dekhne se zyada time concepts samajhne & notes likhne mein lagao.',
    icon: 'terminal',
    color: '#00ff9d',
  },
  {
    id: 'routine-6',
    time: '10:30 AM',
    startTime: '10:30',
    endTime: '11:00',
    title: '☕ Break + Healthy Snack',
    type: 'nutrition',
    category: 'Revision',
    priority: 'low',
    reminderMinutes: 5,
    description: '1 fruit, roasted chana/peanuts, water hydration.',
    icon: 'cafe',
    color: '#ffb800',
  },
  {
    id: 'routine-7',
    time: '11:00 AM–12:15 PM',
    startTime: '11:00',
    endTime: '12:15',
    title: '🧪 Hands-on Lab Practice',
    type: 'hands-on-lab',
    category: 'CTF',
    priority: 'high',
    reminderMinutes: 10,
    description: 'Practice labs and document notes: What I learned, Command, Tool, Vulnerability, Defense.',
    icon: 'flask',
    color: '#00e5ff',
  },
  {
    id: 'routine-8',
    time: '12:30 PM',
    startTime: '12:30',
    endTime: '12:45',
    title: '💉 Afternoon Insulin Routine',
    type: 'health',
    category: 'Revision',
    priority: 'high',
    reminderMinutes: 5,
    description: 'Regular insulin dose as prescribed.',
    icon: 'medkit',
    color: '#ff3b5c',
  },
  {
    id: 'routine-9',
    time: '1:00 PM',
    startTime: '13:00',
    endTime: '13:30',
    title: '🍛 Balanced Lunch',
    type: 'nutrition',
    category: 'Revision',
    priority: 'medium',
    reminderMinutes: 10,
    description: '2 roti, dal, sabzi, curd, protein source (soy/paneer/chana/rajma).',
    icon: 'nutrition',
    color: '#00ff9d',
  },
  {
    id: 'routine-10',
    time: '1:30–2:45 PM',
    startTime: '13:30',
    endTime: '14:45',
    title: '😴 Post-Lunch Rest & Recharge',
    type: 'rest',
    category: 'Revision',
    priority: 'medium',
    reminderMinutes: 5,
    description: '20-40 min relax/nap. Avoid phone scrolling for long-term consistency.',
    icon: 'moon',
    color: '#a855f7',
  },
  {
    id: 'routine-11',
    time: '3:00–4:30 PM',
    startTime: '15:00',
    endTime: '16:30',
    title: '🧪 Practical Cyber Security (Deep Work 2)',
    type: 'practical-cyber',
    category: 'SOC',
    priority: 'high',
    reminderMinutes: 15,
    description: 'Daily practical skill: Wireshark, Splunk, Linux hardening, or detection engineering.',
    icon: 'shield-checkmark',
    color: '#00ff9d',
  },
  {
    id: 'routine-12',
    time: '4:30–5:30 PM',
    startTime: '16:30',
    endTime: '17:30',
    title: '💼 Job Preparation & Applications',
    type: 'job-prep',
    category: 'Interview',
    priority: 'high',
    reminderMinutes: 10,
    description: '30m interview questions, 15m resume/LinkedIn, 15m job applications (2-5 quality applications).',
    icon: 'briefcase',
    color: '#00e5ff',
  },
  {
    id: 'routine-13',
    time: '5:30 PM',
    startTime: '17:30',
    endTime: '18:00',
    title: '🥜 Evening Snack & Hydration',
    type: 'nutrition',
    category: 'Revision',
    priority: 'low',
    reminderMinutes: 5,
    description: 'Roasted chana/peanuts, paneer/soy, optional green tea.',
    icon: 'cafe',
    color: '#ffb800',
  },
  {
    id: 'routine-14',
    time: '6:00–6:45 PM',
    startTime: '18:00',
    endTime: '18:45',
    title: '🏋️ Exercise & Fitness Routine',
    type: 'exercise',
    category: 'Revision',
    priority: 'medium',
    reminderMinutes: 10,
    description: 'Mon/Wed/Fri: Strength training. Tue/Thu/Sat: 30-40m walking. Follow glucose safety.',
    icon: 'barbell',
    color: '#00e5ff',
  },
  {
    id: 'routine-15',
    time: '7:30 PM',
    startTime: '19:30',
    endTime: '19:45',
    title: '💉 Evening Insulin Routine',
    type: 'health',
    category: 'Revision',
    priority: 'high',
    reminderMinutes: 5,
    description: 'Regular insulin dose as prescribed.',
    icon: 'medkit',
    color: '#ff3b5c',
  },
  {
    id: 'routine-16',
    time: '8:00 PM',
    startTime: '20:00',
    endTime: '20:45',
    title: '🍛 Dinner & Relaxation',
    type: 'nutrition',
    category: 'Revision',
    priority: 'medium',
    reminderMinutes: 10,
    description: '2 roti, dal/protein, sabzi, salad.',
    icon: 'restaurant',
    color: '#00ff9d',
  },
  {
    id: 'routine-17',
    time: '9:00–10:00 PM',
    startTime: '21:00',
    endTime: '22:00',
    title: '🧠 Interview Q&A + Day Revision',
    type: 'revision',
    category: 'Interview',
    priority: 'high',
    reminderMinutes: 10,
    description: '20m interview questions, 20m day revision, 20m notes/GitHub documentation.',
    icon: 'book',
    color: '#00ff9d',
  },
  {
    id: 'routine-18',
    time: '10:30 PM',
    startTime: '22:30',
    endTime: '22:45',
    title: '🥛 Plain Milk & 🌙 Lantus Routine',
    type: 'health',
    category: 'Revision',
    priority: 'high',
    reminderMinutes: 5,
    description: '200ml plain milk (no sugar) + prescribed Lantus at fixed time.',
    icon: 'moon',
    color: '#ff3b5c',
  },
  {
    id: 'routine-19',
    time: '11:00 PM',
    startTime: '23:00',
    endTime: '06:45',
    title: '😴 Deep Sleep (7–8 Hours)',
    type: 'rest',
    category: 'Revision',
    priority: 'high',
    reminderMinutes: 15,
    description: 'Quality sleep for muscle recovery & sharp mental focus. Consistency is key!',
    icon: 'bed',
    color: '#a855f7',
  },
];
