import { getTodayString } from '../utils/dateUtils';
import { TaskItem, JobItem, SkillItem, StudySessionItem, SettingsItem } from '../database/db';

export const INITIAL_SKILLS: SkillItem[] = [
  { id: 'skill-1', name: 'Linux Command Line & Hardening', category: 'Linux', progress: 90 },
  { id: 'skill-2', name: 'TCP/IP, OSI & Packet Analysis', category: 'Networking', progress: 80 },
  { id: 'skill-3', name: 'Python Security Automation', category: 'Python', progress: 70 },
  { id: 'skill-4', name: 'Cyber Security Fundamentals & CIA', category: 'Cyber Security Fundamentals', progress: 60 },
  { id: 'skill-5', name: 'Web Security & OWASP Top 10', category: 'Web Security', progress: 50 },
  { id: 'skill-6', name: 'SOC Operations & Alert Triage', category: 'SOC', progress: 40 },
  { id: 'skill-7', name: 'SIEM & Splunk SPL Search', category: 'SIEM', progress: 30 },
  { id: 'skill-8', name: 'Hands-on Projects & Lab Portfolio', category: 'Projects', progress: 40 },
  { id: 'skill-9', name: 'Technical & Behavioral Interview Prep', category: 'Interview', progress: 30 },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-seed-1',
    title: 'Linux Permissions & Bash Scripting',
    description: 'Practice chmod SUID/SGID bits and write bash backup script',
    date: getTodayString(),
    start_time: '09:00',
    end_time: '10:30',
    priority: 'high',
    category: 'Linux',
    status: 'completed',
    recurring: 'daily',
    reminder_minutes: 15,
    created_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
  },
  {
    id: 'task-seed-2',
    title: 'Networking: Wireshark Packet Inspection',
    description: 'Analyze pcap files for 3-way handshake and DNS query anomalies',
    date: getTodayString(),
    start_time: '11:00',
    end_time: '12:30',
    priority: 'high',
    category: 'Networking',
    status: 'completed',
    recurring: 'weekdays',
    reminder_minutes: 30,
    created_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
  },
  {
    id: 'task-seed-3',
    title: 'Nmap Scanning & Host Discovery Practice',
    description: 'Run SYN scans, version detection (-sV), and NSE scripts on Metasploitable lab',
    date: getTodayString(),
    start_time: '14:00',
    end_time: '15:30',
    priority: 'high',
    category: 'Cyber Security Fundamentals',
    status: 'pending',
    recurring: 'none',
    reminder_minutes: 30,
    created_at: new Date().toISOString(),
    completed_at: null,
  },
  {
    id: 'task-seed-4',
    title: 'Splunk SIEM Log Analysis & Threat Hunting',
    description: 'Search failed SSH logins (event_id 4625) and build an alert dashboard',
    date: getTodayString(),
    start_time: '17:00',
    end_time: '18:30',
    priority: 'medium',
    category: 'SIEM',
    status: 'pending',
    recurring: 'weekdays',
    reminder_minutes: 15,
    created_at: new Date().toISOString(),
    completed_at: null,
  },
  {
    id: 'task-seed-5',
    title: 'TryHackMe SOC Analyst Room Practice',
    description: 'Solve 2 alert investigation scenarios on TryHackMe or HackTheBox',
    date: getTodayString(),
    start_time: '20:00',
    end_time: '21:30',
    priority: 'medium',
    category: 'CTF',
    status: 'pending',
    recurring: 'weekly',
    reminder_minutes: 30,
    created_at: new Date().toISOString(),
    completed_at: null,
  },
];

export const INITIAL_JOBS: JobItem[] = [
  {
    id: 'job-seed-1',
    company: 'Deloitte',
    role: 'SOC Analyst L1',
    url: 'https://deloitte.com/careers',
    location: 'Gurugram / Hybrid',
    work_type: 'Hybrid',
    salary: '₹6.5 – 8.0 LPA',
    date_applied: '2026-09-10',
    status: 'Interview',
    interview_date: '2026-09-22 11:00 AM',
    recruiter: 'Priya Sharma (HR)',
    notes: 'Prepare SIEM alert triage, Wireshark TCP stream analysis, and MITRE ATT&CK framework',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'job-seed-2',
    company: 'PwC India',
    role: 'Cybersecurity Consultant',
    url: 'https://pwc.in/careers',
    location: 'Bengaluru',
    work_type: 'On-site',
    salary: '₹7.0 – 9.5 LPA',
    date_applied: '2026-09-05',
    status: 'Assessment',
    interview_date: '2026-09-18 02:00 PM',
    recruiter: 'Arun V.',
    notes: 'Completed technical aptitude round; assessment test pending on network protocols',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'job-seed-3',
    company: 'CrowdStrike',
    role: 'Junior Threat Hunter',
    url: 'https://crowdstrike.com/careers',
    location: 'Remote (India)',
    work_type: 'Remote',
    salary: '₹10.0 – 14.0 LPA',
    date_applied: '2026-09-12',
    status: 'Applied',
    interview_date: null,
    recruiter: 'Global Talent Acquisition',
    notes: 'Applied with custom SOC home lab GitHub repository and TryHackMe top 5% badge',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'job-seed-4',
    company: 'Tata Consultancy Services (TCS)',
    role: 'Security Operations Engineer',
    url: 'https://tcs.com/careers',
    location: 'Hyderabad',
    work_type: 'Hybrid',
    salary: '₹5.5 – 7.0 LPA',
    date_applied: '2026-08-28',
    status: 'Applied',
    interview_date: null,
    recruiter: 'Campus Connect',
    notes: 'Application under review for Q4 hiring drive',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'job-seed-5',
    company: 'Mandiant (Google Cloud)',
    role: 'Incident Response Associate',
    url: 'https://cloud.google.com/mandiant',
    location: 'Remote',
    work_type: 'Remote',
    salary: '₹12.0 – 16.0 LPA',
    date_applied: '2026-09-15',
    status: 'Wishlist',
    interview_date: null,
    recruiter: '',
    notes: 'Dream company! Need deep memory forensics and Volatility tool experience first',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_STUDY_SESSIONS: StudySessionItem[] = [
  {
    id: 'study-seed-1',
    topic: 'Wireshark & Packet Filtering',
    category: 'Networking',
    start_time: '11:00',
    end_time: '12:30',
    duration_minutes: 90,
    date: getTodayString(),
    notes: 'Investigated SYN flood attack logs and extracted HTTP credentials',
    created_at: new Date().toISOString(),
  },
  {
    id: 'study-seed-2',
    topic: 'Linux File Permissions & SUID Escalation',
    category: 'Linux',
    start_time: '09:00',
    end_time: '10:30',
    duration_minutes: 90,
    date: getTodayString(),
    notes: 'Solved privilege escalation challenge using vulnerable find command',
    created_at: new Date().toISOString(),
  },
  {
    id: 'study-seed-3',
    topic: 'Splunk Search Processing Language (SPL)',
    category: 'SIEM',
    start_time: '14:00',
    end_time: '15:20',
    duration_minutes: 80,
    date: getTodayString(),
    notes: 'Created statistical tables using stats count by src_ip and dest_port',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SETTINGS: SettingsItem = {
  id: 'global-settings',
  target_role: 'Cyber Security Analyst / SOC Analyst',
  target_date: '2026-12-31',
  daily_study_target_hours: 6,
  default_reminder_minutes: 30,
  notifications_enabled: 1,
  dark_mode: 1,
  monthly_report_enabled: 1,
};
